// packages/vue/src/components/UserProfile.vue
<script setup lang="ts">
import { useAuth } from '../composables';

const { user, signOut, isLoaded, isSignedIn } = useAuth();

const handleSignOut = () => {
  signOut();
};
</script>

<template>
  <div v-if="isLoaded && isSignedIn && user" class="authify-card" style="max-width: 400px;">
    <div class="authify-profile-info">
      <img
        :src="user.avatarUrl"
        :alt="user.name"
        class="authify-avatar-lg"
      />
      <div>
        <h2 class="authify-title" style="margin: 0; font-size: 20px;">{{ user.name }}</h2>
        <div style="color: #888; font-size: 14px;">{{ user.email }}</div>
      </div>
    </div>

    <div class="authify-input-group">
      <label class="authify-label">User ID</label>
      <div class="authify-monospace">
        {{ user.id }}
      </div>
    </div>

    <div style="margin-top: 24px; display: flex; gap: 10px;">
      <button class="authify-btn authify-btn-secondary">
        Edit Profile
      </button>
      <button
        @click="handleSignOut"
        class="authify-btn authify-btn-primary"
        style="background-color: #ef4444; color: white;"
      >
        Sign Out
      </button>
    </div>
  </div>
</template>

// packages/react/src/components/UserProfile.tsx
import React, { useState } from 'react';
import { useAuth } from '../hooks';
import '@authify/core/styles.css';

export const UserProfile = () => {
    const { user, signOut, isLoaded, isSignedIn } = useAuth();
    const [editing, setEditing] = useState(false);

    if (!isLoaded || !isSignedIn || !user) return null;

    return (
        <div className="authify-card" style={{ maxWidth: '400px' }}>
            <div className="authify-profile-info">
                <img
                    src={user.avatarUrl}
                    alt={user.name}
                    className="authify-avatar-lg"
                />
                <div>
                    <h2 className="authify-title" style={{ margin: 0, fontSize: '20px' }}>{user.name}</h2>
                    <div style={{ color: '#888', fontSize: '14px' }}>{user.email}</div>
                </div>
            </div>

            <div className="authify-input-group">
                <label className="authify-label">User ID</label>
                <div className="authify-monospace">
                    {user.id}
                </div>
            </div>

            <div style={{ marginTop: '24px', display: 'flex', gap: '10px' }}>
                <button
                    className="authify-btn authify-btn-secondary"
                    onClick={() => setEditing(!editing)} // Placeholder
                >
                    Edit Profile
                </button>
                <button
                    className="authify-btn authify-btn-primary"
                    style={{ backgroundColor: '#ef4444', color: '#fff' }}
                    onClick={() => signOut()}
                >
                    Sign Out
                </button>
            </div>
        </div>
    );
};
