// packages/react/src/components/ResetPassword.tsx
import React, { useState, useRef, useEffect } from 'react';
import { useAuth } from '../hooks';

export const ResetPassword = ({ email, onBack, onSuccess }: { email: string, onBack: () => void, onSuccess: () => void }) => {
    const { verifyResetCode, resetPassword, error } = useAuth();
    const [code, setCode] = useState(['', '', '', '', '', '']);
    const [newPassword, setNewPassword] = useState('');
    const [step, setStep] = useState<'verify' | 'reset'>('verify');
    const [loading, setLoading] = useState(false);
    const [successMsg, setSuccessMsg] = useState('');
    const inputRefs = useRef<(HTMLInputElement | null)[]>([]);

    const handleCodeChange = (index: number, value: string) => {
        if (value.length > 1) value = value[0];
        const newCode = [...code];
        newCode[index] = value;
        setCode(newCode);

        // Move to next input
        if (value && index < 5) {
            inputRefs.current[index + 1]?.focus();
        }
    };

    const handleKeyDown = (index: number, e: React.KeyboardEvent) => {
        if (e.key === 'Backspace' && !code[index] && index > 0) {
            inputRefs.current[index - 1]?.focus();
        }
    };

    useEffect(() => {
        const fullCode = code.join('');
        if (fullCode.length === 6 && step === 'verify') {
            handleVerifyCode(fullCode);
        }
    }, [code]);

    const handleVerifyCode = async (fullCode: string) => {
        setLoading(true);
        try {
            await verifyResetCode(email, fullCode);
            setStep('reset');
        } catch (err) {
            // Error handled by store
        } finally {
            setLoading(false);
        }
    };

    const handleResetPassword = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);
        try {
            await resetPassword(email, code.join(''), newPassword);
            setSuccessMsg('Your password has been reset successfully!');
            setTimeout(onSuccess, 3000);
        } catch (err) {
            // Error handled by store
        } finally {
            setLoading(false);
        }
    };

    if (successMsg) {
        return (
            <div className="authify-card" style={{ textAlign: 'center' }}>
                <div style={{ fontSize: '48px', marginBottom: '16px' }}>✅</div>
                <h2 className="authify-title">Success!</h2>
                <p style={{ color: '#059669', fontWeight: '500' }}>{successMsg}</p>
                <p style={{ color: '#666', marginTop: '12px' }}>Redirecting to sign in...</p>
            </div>
        );
    }

    return (
        <div className="authify-card">
            <div style={{ color: '#059669', backgroundColor: '#ecfdf5', padding: '12px', borderRadius: '8px', marginBottom: '20px', fontSize: '14px', textAlign: 'center' }}>
                ✅ Reset code sent to your email!
            </div>
            <h2 className="authify-title">{step === 'verify' ? 'Verify Code' : 'New Password'}</h2>
            <p style={{ color: '#666', marginBottom: '24px' }}>
                {step === 'verify' 
                    ? `Enter the 6-digit code sent to ${email}`
                    : 'Enter your new password below.'}
            </p>

            {error && <div className="authify-error">{error}</div>}

            {step === 'verify' ? (
                <div style={{ display: 'flex', gap: '8px', justifyContent: 'center', marginBottom: '24px' }}>
                    {code.map((digit, idx) => (
                        <input
                            key={idx}
                            ref={el => inputRefs.current[idx] = el}
                            type="password"
                            maxLength={1}
                            value={digit}
                            onChange={e => handleCodeChange(idx, e.target.value)}
                            onKeyDown={e => handleKeyDown(idx, e)}
                            className="authify-input"
                            style={{ width: '45px', textAlign: 'center', fontSize: '20px' }}
                            autoComplete="one-time-code"
                        />
                    ))}
                </div>
            ) : (
                <form onSubmit={handleResetPassword}>
                    <div className="authify-input-group">
                        <label className="authify-label">New Password</label>
                        <input
                            type="password"
                            value={newPassword}
                            onChange={e => setNewPassword(e.target.value)}
                            className="authify-input"
                            required
                            placeholder="••••••••"
                        />
                    </div>
                    <button
                        type="submit"
                        disabled={loading}
                        className="authify-btn authify-btn-primary"
                    >
                        {loading ? 'Resetting...' : 'Reset Password'}
                    </button>
                </form>
            )}

            <button
                onClick={onBack}
                className="authify-btn authify-btn-secondary"
                style={{ marginTop: '12px' }}
            >
                Cancel
            </button>
        </div>
    );
};

// packages/vue/src/components/ResetPassword.vue
<template>
  <div v-if="successMsg" class="authify-card" style="text-align: center">
    <div style="font-size: 48px; margin-bottom: 16px">✅</div>
    <h2 class="authify-title">Success!</h2>
    <p style="color: #059669; font-weight: 500">{{ successMsg }}</p>
    <p style="color: #666; margin-top: 12px">Redirecting to sign in...</p>
  </div>

  <div v-else class="authify-card">
    <div style="color: #059669; background-color: #ecfdf5; padding: 12px; border-radius: 8px; margin-bottom: 20px; font-size: 14px; text-align: center">
      ✅ Reset code sent to your email!
    </div>
    <h2 class="authify-title">
      {{ step === 'verify' ? 'Verify Code' : 'New Password' }}
    </h2>
    <p style="color: #666; margin-bottom: 24px">
      {{
        step === 'verify'
          ? 'Enter the 6-digit code sent to ' + email
          : 'Enter your new password below.'
      }}
    </p>

    <div v-if="error" class="authify-error">{{ error }}</div>

    <div
      v-if="step === 'verify'"
      style="display: flex; gap: 8px; justify-content: center; margin-bottom: 24px"
    >
      <input
        v-for="(digit, idx) in code"
        :key="idx"
        :ref="el => (inputRefs[idx] = el as HTMLInputElement)"
        v-model="code[idx]"
        type="password"
        maxlength="1"
        class="authify-input"
        style="width: 45px; text-align: center; font-size: 20px"
        autocomplete="one-time-code"
        @input="handleInput(idx)"
        @keydown.delete="handleDelete(idx)"
      />
    </div>

    <form v-else @submit.prevent="handleReset">
      <div class="authify-input-group">
        <label class="authify-label">New Password</label>
        <input
          v-model="newPassword"
          type="password"
          class="authify-input"
          required
          placeholder="••••••••"
        />
      </div>
      <button
        type="submit"
        :disabled="loading"
        class="authify-btn authify-btn-primary"
      >
        {{ loading ? 'Resetting...' : 'Reset Password' }}
      </button>
    </form>

    <button
      @click="$emit('back')"
      class="authify-btn authify-btn-secondary"
      style="margin-top: 12px"
    >
      Cancel
    </button>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, onMounted } from 'vue';
import { useAuth } from '../composables';

const props = defineProps<{ email: string }>();
const emit = defineEmits(['back', 'success']);

const { verifyResetCode, resetPassword, error } = useAuth();
const code = ref(['', '', '', '', '', '']);
const newPassword = ref('');
const step = ref<'verify' | 'reset'>('verify');
const loading = ref(false);
const successMsg = ref('');
const inputRefs = ref<HTMLInputElement[]>([]);

const handleInput = (idx: number) => {
  if (code.value[idx] && idx < 5) {
    inputRefs.value[idx + 1]?.focus();
  }
};

const handleDelete = (idx: number) => {
  if (!code.value[idx] && idx > 0) {
    inputRefs.value[idx - 1]?.focus();
  }
};

watch(code, (newVal) => {
  const fullCode = newVal.join('');
  if (fullCode.length === 6 && step.value === 'verify') {
    handleVerify(fullCode);
  }
}, { deep: true });

const handleVerify = async (fullCode: string) => {
  loading.value = true;
  try {
    await verifyResetCode(props.email, fullCode);
    step.value = 'reset';
  } catch (err) {
    // Handled by store
  } finally {
    loading.value = false;
  }
};

const handleReset = async () => {
  loading.value = true;
  try {
    await resetPassword(props.email, code.value.join(''), newPassword.value);
    successMsg.value = 'Your password has been reset successfully!';
    setTimeout(() => emit('success'), 3000);
  } catch (err) {
    // Handled by store
  } finally {
    loading.value = false;
  }
};

onMounted(() => {
  inputRefs.value[0]?.focus();
});
</script>
